app_name: Wingman
target:
  default: phone_link
  paste_mode: focus_phone_link
targets:
  phone_link:
    process_names:
    - PhoneExperienceHost.exe
    - YourPhone.exe
    - YourPhoneAppProxy.exe
    window_titles:
    - Tinder
    - Link to Windows
    - Your Phone
    mode: uia_first_ocr_fallback
    chat_crop:
      left: 0.0
      top: 0.0
      right: 1.0
      bottom: 1.0
    profile_crop:
      left: 0.6
      top: 0.08
      right: 0.98
      bottom: 0.92
  browser_edge:
    process_name: msedge.exe
    url_patterns:
    - '*tinder.com/*'
    - '*hinge.co/*'
    - '*bumble.com/*'
    mode: ocr_only
    chat_crop:
      left: 0.22
      top: 0.14
      right: 0.88
      bottom: 0.9
    profile_crop:
      left: 0.04
      top: 0.1
      right: 0.4
      bottom: 0.92
  browser_chrome:
    process_name: chrome.exe
    url_patterns:
    - '*tinder.com/*'
    - '*hinge.co/*'
    - '*bumble.com/*'
    mode: ocr_only
    chat_crop:
      left: 0.22
      top: 0.14
      right: 0.88
      bottom: 0.9
    profile_crop:
      left: 0.04
      top: 0.1
      right: 0.4
      bottom: 0.92
model:
  base_url: http://10.0.0.246:11434
  model_name: gpt-oss:latest
  temperature: 0.6
  max_tokens: 512
  keep_alive: 45m
  request_timeout_seconds: 300
  use_tools: false
scraping:
  scraping: null
  capture:
    prefer_dxcam: true
    fallback_mss: true
    force_full_window: true
  prefer_dxcam: true
  fallback_mss: true
  output_index_override: null
  try_all_outputs: true
  tesseract_path: C:\Program Files\Tesseract-OCR\tesseract.exe
  monitors:
  - hmonitor: 827261323
    left: 2560
    top: 52
    right: 4480
    bottom: 1252
    width: 1920
    height: 1200
    dpiX: 96
    dpiY: 96
    scale: 1.0
  - &id001
    hmonitor: 2014839895
    left: 0
    top: 0
    right: 2560
    bottom: 1440
    width: 2560
    height: 1440
    dpiX: 96
    dpiY: 96
    scale: 1.0
  active_monitor: *id001
  selected_hwnd: null
ui:
  suggestions: 5
  ask_question_default: often
  max_reply_chars: 1200
  topmost: true
  show_tray_icon: false
behavior:
  throttle_seconds_per_chat: 8
  allow_explicit: true
storage:
  base_dir: ./data
  people_dir: ./data/people
  sqlite_path: ./data/wingman.db
logging:
  dir: ./logs
  level: INFO
integrations:
  n8n:
    enabled: false
    webhook_url: ''
ahk:
  exe_path: C:\Users\leviw\AppData\Local\Programs\AutoHotkey\v2\AutoHotkey64.exe
  paste_strategy: type
input:
  focus_settle_ms: 400
  wait_ms_before_type: 1200
  type_per_char_delay_ms: 20
  focus_alt_trick: true
vision:
  enabled: true
  base_url: http://10.0.0.246:11434
  model_name: llava:latest
  request_timeout_seconds: 45
  clicks: 1
  between_click_ms: 80
  wait_ms_after_click: 350
  prompt: 'You are looking at a desktop app screenshot. Find the text input field
    where a user would type a chat message. Return ONLY JSON like {"x":123,"y":456}.

    '
